version: '3'

services:
  frontend:
    image: aviaurez/time-app-frontend
    restart: always
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
  api:
    image: aviaurez/time-app-api-dev
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
    environment:
      MYSQL_HOST : mysql
      MYSQL_USER : root
      MYSQL_PORT : '3306'
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: time_db
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data_pub:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8021:8000'

volumes:
  mysql_data_pub: