version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
  api:
    build: ./api
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8021:8000'

volumes:
  mysql_data: